### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by rubyandcoffee** [rubyandcoffee/job_sorter#1]
**Specs:**

- [x] If Job list (input) is empty, return empty sequence
- [x] Job list (input) must be a String
- [x] Job sorter function must return a String
- [x] Job sorter function must return String in given order according to jobs and dependencies
- [x] Job sorter return value must contain exactly the same characters as job_input contained
- [x] If a job list (input) has self-dependency, then this must raise self-dependency error
- [x] If a job list (input) has circular dependencies, then this must raise circular dependencies error

**Class:**

- [x] Takes in job list input as a String with this format: `'a => , b => c, c =>'`
- [x] Split it into jobs and dependencies
- [x] Put this into a Hash
- [x] TSort the hash into order depending on jobs and dependencies
- [x] Return result as a String: `'a c b'`

**README:**

- [x] Give a problem definition
- [x] Explain how to use the gem
